# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch


# Create random tensor
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.0348, 0.2700, 0.6625, 0.4542, 0.0267, 0.8287, 0.8007],
        [0.3859, 0.1676, 0.2407, 0.4057, 0.2200, 0.4350, 0.0950],
        [0.9552, 0.6696, 0.8233, 0.7697, 0.8408, 0.6773, 0.4243],
        [0.4725, 0.7008, 0.6108, 0.7992, 0.1766, 0.9839, 0.4372],
        [0.6277, 0.1825, 0.2261, 0.7478, 0.0877, 0.6548, 0.1390],
        [0.4578, 0.1030, 0.0337, 0.7701, 0.3590, 0.9297, 0.9905],
        [0.8758, 0.9083, 0.5369, 0.8839, 0.6484, 0.5967, 0.0603]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor

# Perform matrix multiplication 
tensor = random_tensor @ torch.rand(7, 7).T
print(tensor)


tensor([[1.8232, 2.3545, 1.4148, 1.1863, 1.5616, 1.7197, 1.6481],
        [1.0893, 1.2613, 0.8750, 1.0300, 1.1437, 1.2468, 1.1571],
        [2.9646, 3.2155, 2.5932, 2.6045, 2.6649, 3.2333, 2.8965],
        [2.5077, 2.8916, 1.8719, 2.1854, 2.3907, 2.3546, 2.5284],
        [1.3495, 1.7322, 1.1053, 1.4461, 1.8057, 1.6508, 1.6347],
        [1.8706, 2.4913, 1.4422, 1.6264, 2.2575, 2.2799, 1.8213],
        [2.6585, 2.7543, 2.1805, 2.6026, 2.5285, 2.6426, 2.7239]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
tensor = tensor1 @ tensor2.T
print(tensor)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
tensor = tensor1 @ tensor2.T
print(tensor)

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]])


### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max_value = torch.max(tensor)
print(max_value)

# Find min
min_value = torch.min(tensor)
print(min_value)

tensor(1.0651)
tensor(0.3129)


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
max_index = torch.argmax(tensor)
print(max_index)

# Find arg min
min_index = torch.argmin(tensor)
print(min_index)

tensor(2)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
print(tensor)
# Remove single dimensions
tensor = tensor.squeeze()

# Print out tensors and their shapes
print(tensor)
print(tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
